// Стилът на Login страницата ползва CSS променливите от theme.js, така че
// автоматично се променя според избраната тема (light / dark / pink) — същата
// логика като Layout-а на останалите страници.

export const loginStyles = {
  page: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'var(--bg)',
    color: 'var(--text)',
    fontFamily: "'Inter', sans-serif",
    padding: '24px 16px',
    boxSizing: 'border-box',
  },
  themeBtnWrap: {
    position: 'absolute',
    top: 16,
    right: 16,
    zIndex: 10,
  },
  themeBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    border: '1px solid var(--border)',
    background: 'var(--input-bg)',
    color: 'var(--text-muted)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    flexShrink: 0,
  },
  brand: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    marginBottom: 24,
    width: '100%',
    maxWidth: 420,
  },
  brandIcon: {
    width: 40,
    height: 40,
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    borderRadius: 12,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 1px 3px rgba(0,0,0,0.06)',
    overflow: 'hidden',
  },
  brandIconImage: {
    width: '88%',
    height: '88%',
    objectFit: 'contain',
  },
  brandName: {
    fontSize: 17,
    fontWeight: 600,
    color: 'var(--text)',
    letterSpacing: -0.4,
  },
  brandSub: {
    fontSize: 11,
    color: 'var(--text-muted)',
    marginTop: 1,
    letterSpacing: 2.4,
  },
  card: {
    width: '100%',
    maxWidth: 420,
    background: 'var(--card-bg)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--border)',
    borderRadius: 20,
    padding: '24px 24px 24px',
    boxShadow: '0 4px 16px rgba(0,0,0,0.04), 0 1px 3px rgba(0,0,0,0.04)',
    boxSizing: 'border-box',
  },
  bannerWrap: {
    width: '100%',
    background: 'var(--input-bg)',
    borderRadius: 14,
    overflow: 'hidden',
    border: '1px solid var(--border)',
    marginBottom: 20,
    boxShadow: '0 1px 3px rgba(0,0,0,0.04)',
  },
  banner: {
    display: 'block',
    width: '100%',
    height: 128,
    objectFit: 'cover',
    objectPosition: 'center 42%',
  },
  greeting: {
    fontSize: 20,
    fontWeight: 600,
    color: 'var(--text)',
    letterSpacing: -0.4,
    marginBottom: 3,
  },
  greetingSub: {
    fontSize: 13,
    color: 'var(--text-muted)',
    marginBottom: 22,
    lineHeight: 1.5,
  },
  tabs: {
    display: 'flex',
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--border)',
    marginBottom: 20,
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: 13,
  },
  grid2: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))',
    gap: 10,
  },
  label: {
    fontSize: 11,
    fontWeight: 500,
    color: 'var(--text-muted)',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  error: {
    fontSize: 12,
    color: '#ef4444',
    padding: '8px 12px',
    background: '#fef2f2',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#fecaca',
    borderRadius: 8,
  },
  success: {
    fontSize: 13,
    color: '#16a34a',
    padding: '12px 14px',
    background: '#f0fdf4',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#bbf7d0',
    borderRadius: 8,
    lineHeight: 1.5,
  },
  note: {
    fontSize: 11,
    color: 'var(--text-muted)',
    textAlign: 'center',
    lineHeight: 1.5,
  },
  helperRow: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 12,
    flexWrap: 'wrap',
  },
  linkBtn: {
    padding: 0,
    background: 'none',
    border: 'none',
    color: 'var(--text)',
    fontFamily: "'Inter', sans-serif",
    fontSize: 12,
    fontWeight: 500,
    cursor: 'pointer',
    textDecoration: 'none',
  },
  footer: {
    display: 'flex',
    justifyContent: 'space-between',
    width: '100%',
    maxWidth: 420,
    marginTop: 14,
    padding: '0 2px',
  },
  footerText: {
    fontSize: 11,
    color: 'var(--text-light)',
  },
  footerLink: {
    fontSize: 11,
    color: 'var(--text-muted)',
    textDecoration: 'none',
  },
}

export const fieldStyle = {
  display: 'flex',
  flexDirection: 'column',
  gap: 5,
}

export function getTabStyle(isActive) {
  return {
    padding: '7px 14px',
    background: 'none',
    border: 'none',
    borderBottomWidth: 2,
    borderBottomStyle: 'solid',
    borderBottomColor: isActive ? 'var(--accent)' : 'transparent',
    fontFamily: "'Inter', sans-serif",
    fontSize: 13,
    fontWeight: 500,
    color: isActive ? 'var(--text)' : 'var(--text-muted)',
    cursor: 'pointer',
    marginBottom: -1,
    outline: 'none',
  }
}

export const inputWrapStyle = {
  position: 'relative',
  width: '100%',
}

export const inputIconStyle = {
  position: 'absolute',
  left: 12,
  top: '50%',
  transform: 'translateY(-50%)',
  color: 'var(--text-muted)',
  pointerEvents: 'none',
  display: 'flex',
  alignItems: 'center',
  zIndex: 1,
}

export function getInputStyle(focused, withRightIcon = false) {
  return {
    width: '100%',
    background: 'var(--input-bg)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: focused ? 'var(--accent)' : 'var(--border)',
    borderRadius: 8,
    padding: withRightIcon ? '10px 38px 10px 38px' : '10px 12px 10px 38px',
    fontFamily: "'Inter', sans-serif",
    fontSize: 14,
    color: 'var(--text)',
    outline: 'none',
    boxSizing: 'border-box',
    WebkitAppearance: 'none',
    transition: 'border-color 0.15s, background 0.15s',
  }
}

export const eyeBtnStyle = {
  position: 'absolute',
  right: 8,
  top: '50%',
  transform: 'translateY(-50%)',
  width: 28,
  height: 28,
  border: 'none',
  background: 'transparent',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  cursor: 'pointer',
  color: 'var(--text-muted)',
  borderRadius: 6,
  padding: 0,
  zIndex: 2,
}

export function getButtonStyle(dimmed) {
  return {
    width: '100%',
    padding: '10px',
    background: 'var(--btn-bg)',
    border: 'none',
    borderRadius: 10,
    color: 'var(--btn-color)',
    fontFamily: "'Inter', sans-serif",
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginTop: 2,
    boxShadow: '0 4px 12px rgba(0,0,0,0.08)',
    opacity: dimmed ? 0.7 : 1,
  }
}
