export const profileStyles = {
  input: {
    width: '100%',
    background: 'var(--input-bg)',
    border: '1px solid var(--border)',
    borderRadius: 8,
    padding: '9px 12px',
    fontFamily: "'Inter', sans-serif",
    fontSize: 13,
    color: 'var(--text)',
    outline: 'none',
    boxSizing: 'border-box',
  },
  mutedInput: {
    width: '100%',
    background: 'var(--input-bg)',
    border: '1px solid var(--border)',
    borderRadius: 8,
    padding: '9px 12px',
    fontFamily: "'Inter', sans-serif",
    fontSize: 13,
    color: 'var(--text-muted)',
    outline: 'none',
    boxSizing: 'border-box',
  },
  primaryButton: {
    width: '100%',
    padding: 10,
    background: 'var(--btn-bg)',
    border: 'none',
    borderRadius: 8,
    color: 'var(--btn-color)',
    fontFamily: "'Inter', sans-serif",
    fontSize: 13,
    fontWeight: 500,
    cursor: 'pointer',
  },
  fieldWrap: {
    display: 'flex',
    flexDirection: 'column',
    gap: 5,
  },
  fieldLabel: {
    fontSize: 11,
    fontWeight: 500,
    color: 'var(--text-muted)',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  main: {
    background: 'var(--bg)',
    minHeight: 'calc(100vh - 56px)',
  },
  header: {
    marginBottom: 24,
  },
  title: {
    fontSize: 22,
    fontWeight: 600,
    letterSpacing: -0.5,
    color: 'var(--text)',
    marginBottom: 3,
  },
  subtitle: {
    fontSize: 13,
    color: 'var(--text-muted)',
  },
  column: {
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },
  sectionCard: {
    background: 'var(--card-bg)',
    border: '1px solid var(--border)',
    borderRadius: 12,
    padding: '20px 24px',
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 600,
    color: 'var(--text)',
    marginBottom: 16,
  },
  sectionTitleCompact: {
    fontSize: 14,
    fontWeight: 600,
    color: 'var(--text)',
    marginBottom: 4,
  },
  groupedSectionHeader: {
    marginBottom: 18,
  },
  sectionSubtitle: {
    fontSize: 13,
    color: 'var(--text-muted)',
    marginBottom: 16,
    lineHeight: 1.5,
  },
  successNotice: {
    fontSize: 12,
    color: '#16a34a',
    padding: '8px 12px',
    background: '#f0fdf4',
    border: '1px solid #bbf7d0',
    borderRadius: 8,
    marginBottom: 12,
  },
  requestSuccessNotice: {
    fontSize: 12,
    color: '#16a34a',
    padding: '8px 12px',
    background: '#f0fdf4',
    border: '1px solid #bbf7d0',
    borderRadius: 8,
    marginBottom: 12,
  },
  errorNotice: {
    fontSize: 12,
    color: '#ef4444',
    padding: '8px 12px',
    background: '#fef2f2',
    border: '1px solid #fecaca',
    borderRadius: 8,
    marginBottom: 12,
  },
  stack: {
    display: 'flex',
    flexDirection: 'column',
    gap: 13,
  },
  twoColumnGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 10,
  },
  settingsGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 14,
    alignItems: 'start',
  },
  settingPanel: {
    background: 'var(--input-bg)',
    border: '1px solid var(--border)',
    borderRadius: 10,
    padding: '16px 16px 14px',
  },
  settingPanelWide: {
    gridColumn: '1 / -1',
  },
  avatarRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 16,
    flexWrap: 'wrap',
  },
  avatarWrap: {
    width: 72,
    height: 72,
    borderRadius: '50%',
    background: 'var(--input-bg)',
    border: '1px solid var(--border)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: '50%',
    objectFit: 'cover',
  },
  avatarInitials: {
    fontSize: 22,
    fontWeight: 600,
    color: 'var(--text-muted)',
  },
  hiddenFileInput: {
    display: 'none',
  },
  uploadButton: {
    padding: '8px 14px',
    background: 'var(--input-bg)',
    border: '1px solid var(--border)',
    borderRadius: 8,
    fontFamily: "'Inter', sans-serif",
    fontSize: 12,
    fontWeight: 500,
    cursor: 'pointer',
    color: 'var(--text)',
  },
  uploadHint: {
    fontSize: 11,
    color: 'var(--text-muted)',
    marginTop: 6,
  },
  requestStack: {
    display: 'flex',
    flexDirection: 'column',
    gap: 14,
  },
  requestStatusInput: {
    width: '100%',
    background: 'var(--input-bg)',
    border: '1px solid var(--border)',
    borderRadius: 8,
    padding: '9px 12px',
    fontFamily: "'Inter', sans-serif",
    fontSize: 13,
    color: 'var(--text-muted)',
    outline: 'none',
    boxSizing: 'border-box',
  },
  requestTextarea: {
    width: '100%',
    background: 'var(--input-bg)',
    border: '1px solid var(--border)',
    borderRadius: 8,
    padding: '10px 12px 9px',
    fontFamily: "'Inter', sans-serif",
    fontSize: 13,
    color: 'var(--text)',
    outline: 'none',
    boxSizing: 'border-box',
    minHeight: 96,
    resize: 'vertical',
    lineHeight: 1.5,
  },
  requestList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  requestPendingCard: {
    padding: '12px 14px',
    background: '#fffbeb',
    border: '1px solid #fde68a',
    borderRadius: 8,
  },
  requestAnsweredCard: {
    padding: '12px 14px',
    background: 'var(--input-bg)',
    border: '1px solid var(--border)',
    borderRadius: 8,
  },
  requestHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: 4,
    gap: 8,
    flexWrap: 'wrap',
  },
  pendingRequestTitle: {
    fontSize: 13,
    fontWeight: 500,
    color: '#1a1a1a',
  },
  answeredRequestTitle: {
    fontSize: 13,
    fontWeight: 500,
    color: 'var(--text)',
  },
  pendingMessage: {
    fontSize: 12,
    color: '#888',
    lineHeight: 1.5,
  },
  answeredMessage: {
    fontSize: 12,
    color: 'var(--text-muted)',
    lineHeight: 1.5,
    marginBottom: 8,
  },
  pendingMeta: {
    fontSize: 11,
    color: '#b0b0a8',
    marginTop: 4,
  },
  answeredMeta: {
    fontSize: 11,
    color: 'var(--text-light)',
    marginTop: 6,
  },
  responseBox: {
    padding: '10px 12px',
    background: 'var(--card-bg)',
    border: '1px solid var(--border)',
    borderRadius: 8,
  },
  responseLabel: {
    fontSize: 11,
    fontWeight: 500,
    color: 'var(--text-muted)',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 6,
  },
  responseText: {
    fontSize: 12,
    color: 'var(--text)',
    lineHeight: 1.5,
  },
}

export function getRequestSubmitButtonStyle(disabled) {
  return {
    ...profileStyles.primaryButton,
    opacity: disabled ? 0.5 : 1,
  }
}

export function getStatusBadgeStyle(styleConfig) {
  return {
    fontSize: 11,
    fontWeight: 500,
    padding: '3px 8px',
    borderRadius: 20,
    ...styleConfig,
  }
}
